# Generated by Django 6.1.1 on 2026-10-01 19:23

import core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0003_alter_job_status_job_job_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_snapshot',
            field=models.FileField(blank=True, help_text='Copy of resume at time of application', null=True, upload_to='application_resumes/', validators=[core.validators.validate_resume_file]),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('offer_extended', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='app_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'job'], name='app_status_job_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'applicant'], name='app_status_app_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='app_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='app_applicant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', '-applied_at'], name='app_job_applied_idx'),
        ),
    ]
