# Generated by Django 6.1.1 on 2026-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
