# Generated by Django 6.1.1 on 2026-10-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.CharField(blank=True, choices=[('moderator', 'Moderator'), ('superadmin', 'Superadmin')], default='moderator', max_length=20),
        ),
    ]
