# Generated by Django 6.1.1 on 2026-10-01 19:23

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[core.validators.validate_resume_file]),
        ),
    ]
